package com.example.allthingsf1

enum class CountryCodes(var country : String) {
    ARGENTINA("Argentina"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    AZERBAIJAN("Azerbaijan"),
    BAHRAIN("Bahrain"),
    BELGIUM("Belgium"),
    BRAZIL("Brazil"),
    CANADA("Canada"),
    CHINA("China"),
    FRANCE("France"),
    GERMANY("Germany"),
    HUNGARY("Hungary"),
    INDIA("India"),
    ITALY("Italy"),
    JAPAN("Japan"),
    MALAYSIA("Malaysia"),
    MEXICO("Mexico"),
    MONACO("Monaco"),
    MOROCCO("Morocco"),
    NETHERLANDS("Netherlands"),
    PORTUGAL("Portugal"),
    RUSSIA("Russia"),
    SINGAPORE("Singapore"),
    SOUTH_AFRICA("South Africa"),
    KOREA("Korea"),
    SPAIN("Spain"),
    SWEDEN("Sweden"),
    SWITZERLAND("Switzerland"),
    TURKEY("Turkey"),
    UAE("UAE"),
    UK("UK"),
    USA("USA")
}

enum class FlagCodes(var code: String) {
    ARGENTINA("ar"),
    AUSTRALIA("au"),
    AUSTRIA("at"),
    AZERBAIJAN("az"),
    BAHRAIN("bh"),
    BELGIUM("be"),
    BRAZIL("br"),
    CANADA("ca"),
    CHINA("cn"),
    FRANCE("fr"),
    GERMANY("de"),
    HUNGARY("hu"),
    INDIA("in"),
    ITALY("it"),
    JAPAN("jp"),
    MALAYSIA("my"),
    MEXICO("mx"),
    MONACO("mc"),
    MOROCCO("ma"),
    NETHERLANDS("nl"),
    PORTUGAL("pt"),
    RUSSIA("ru"),
    SINGAPORE("sg"),
    SOUTH_AFRICA("za"),
    KOREA("kr"),
    SPAIN("es"),
    SWEDEN("se"),
    SWITZERLAND("ch"),
    TURKEY("tr"),
    UAE("ae"),
    UK("gb"),
    USA("us")
}

